name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - name: Run specs
      run: |
        gem install bundler -v 2.2.15
        bundle install
        bundle exec rake
    - name: Run rubocop
      run: |
        gem install bundler -v 2.2.15
        bundle install
        bundle exec rubocop
    - name: Run bundler-audit
      run: |
        gem install bundler -v 2.2.15
        bundle install
        bundle exec bundler-audit
